version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    depends_on:
      - db
    restart: always
    env_file: .env

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always
    env_file: .env

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    env_file: .env

volumes:
  postgres_data: 